🩹Isolate Templete and Infra IasC

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -117,10 +117,10 @@ jobs:
 
       - name: Validate
         run: |
-          terraform validate && echo "✅"
+          terraform validate && echo "✅" || echo "💥"
 
       - name: Apply
         run: |
           terraform apply -var="environment=$ENVIRONMENT" -auto-approve && \
-             printf '%s\n' '✨✨✨' "✨✨Deploy ${{ inputs.ENVIRONMENT }}🍻" '✨' || \
-                printf '%s\n' '🔥🔥🔥' '🔥🔥Error to Deploy🚑️' '🔥'
+             printf '%s\n' '✨✨✨' "✨✨Deploy ${{ inputs.ENVIRONMENT }}    🍻" '✨' || \
+                printf '%s\n' '🔥🔥🔥' '🔥🔥Error to Deploy    🚑️' '🔥'
